# Docs: https://geshan.com.np/blog/2021/12/docker-postgres/ -> might have a way to run seed.sql
version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - frontend:/app/
      - /app/node_modules
    depends_on:
      - backend
      - postgres
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - backend:/app/
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres # container name of database (docker-compose networking)
      - DB_PASS=postgres
      - DB_PORT=5432
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  frontend:
    driver: local
  backend:
    driver: local
  postgres:
    driver: local
  